### ISSUE TITLE
Create User Personas

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/documentation#16]
### Task
Create 2-5 personas that will represent different users of our application with varying levels of permissions. 
The basic ones would be requesters, approvers and administrators. 

_PS: We might want some input from the stakeholder to help guide us here. There are some clues in the [requirements docs](https://docs.google.com/document/d/1hBX_Ga2x4-TGXqEVKQyvHXmiRDEbaLFYx-VBFVYHa80/edit) but it mostly refers to external / internal and club / non-club users._

### Why

For sprint 1, we need our first set of user personas to capture the needs of different people that will be interacting with our application. This will also play well with the User Management Epic (CSU-Booking-Platform/application#46) as it will make it easier for us to define the permissions and roles that the system will be built around. 

### Tools

A site we've used for 390 that helped us with personas was : https://app.xtensio.com/design/mf4i2o8e

**Comment by Alex-Hayeur** [comment]
Personas for first sprint can be found here, let me know if we can close the issue or if we need changes made/more personas
https://drive.google.com/drive/folders/1q8YusQcR65Pzv0VM4OcnKR696VL8DeUk
